# Generated by Django 4.1.7 on 2023-03-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_falcuty_livestream_info_post_category_slider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post_category',
            old_name='title',
            new_name='name',
        ),
    ]
