# Generated by Django 4.1.7 on 2023-03-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_post_category_post_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='post_category',
        ),
    ]
