# Generated by Django 4.1.7 on 2023-03-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_name_post_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='post_category', to='courses.post_category'),
        ),
    ]
