# Generated by Django 4.1.7 on 2023-03-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_post_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/courses/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='university_info',
            name='logo_url',
            field=models.ImageField(default=None, null=True, upload_to='static/avt/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/users/%Y/%m/'),
        ),
    ]
