# Generated by Django 4.1.7 on 2023-03-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_image_alter_university_info_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='university_info',
            name='logo_url',
            field=models.ImageField(default=None, null=True, upload_to='avt/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='users/%Y/%m/'),
        ),
    ]
