# Generated by Django 4.1.7 on 2023-03-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_user_address_user_phone_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
